#!/bin/bash

read -p "enter total no. of user to add: " num

for (( i=1; i<=$num; i++ ))
do
        read -p "enter user name: " user
        sudo useradd -m $user
        echo "User $user created successfully!!"
done
